config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :cars, only: [:index, :show] do
    resources :reviews, only: [:create]
      resources :favourites, only: [:new, :create]
  end

  resources :favourites, only: [:index, :destroy]
  resources :reviews, only: [:destroy]
  resources :pages , only: [:index]

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :owner
  has_many :reviews
  has_many :favourites, dependent: :destroy

  validates :brand, :model, :fuel, presence: true
  validates :year, presence: true, numericality: { only_integer: true }
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :car
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :cars, dependent: :destroy

  validates :nickname, uniqueness: true, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car
  validates :rating, length: { maximum: 5 }
  validates :comment, length: { minimum: 6, too_short: "must have atleast 6 characters" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
    @review = Review.new
    @favourite = Favourite.new
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
def index
  @favourites = Favourite.all
end

  def create
    @car = Car.find(params[:car_id])
    @favourite = Favourite.new
    @favourite.car = @car

    if @favourite.save
      redirect_to car_path(@car)
    else
      render 'cars/show', status: :unprocessable_entity
    end
  end

  def destroy
    @favourite = Favourite.find(params[:id])
    @favourite.destroy
    redirect_to favourites_path, status: :see_other
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @car = Car.find(params[:car_id])
    @review = Review.new(review_params)
    @review.car = @car
    if @review.save
      redirect_to car_path(@car)
    else
      render 'cars/show', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cars/index.html.erb
<h1>Awesome Garage</h1>
<ul>
  <% @cars.each do |car| %>
   <li><%= link_to car.brand, car_path(car) %></li>
  <% end %>
</ul>

app/views/cars/show.html.erb
<h3><%= @car.brand %></h3>
<h3><%= @car.model %></h3>
<h3><%= @car.fuel %></h3>
<h3><%= @car.year %></h3>

<% if @car.favourites.empty? %>
  <%= simple_form_for [@car, @favourite] do |f| %>
    <%= f.submit "Add to your Garage", class:"btn btn-primary" %>
  <% end %>
<% else %>
  <p>This car is already in your Garage!</p>
<% end %>



<%= simple_form_for [@car, @review] do |f| %>
  <%= f.input :comment %>
  <%= f.input :rating, collection: 1..5 %>
  <%= f.submit "Submit review", class:"btn btn-primary" %>
<% end %>

<h2>Reviews:</h2>
<% @car.reviews.each do |review| %>
<p><%= review.comment %></p>
<p><%= review.rating %></p>
<% end %>

<%= link_to 'Your garage', favourites_path, class: "btn btn-primary" %>
<%= link_to 'Main Page', cars_path, class: "btn btn-primary" %>

app/views/favourites/index.html.erb
<h1>My Garage</h1>
<ul>
<% @favourites.each do |favourite| %>
  <p><%= favourite.car.brand %></p>
  <%= link_to "Delete",
    favourite_path(favourite),
    data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}%>

<% end %>
</ul>

<%= link_to 'Main Page', cars_path, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAwesomeGarage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class = "container mt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Landing Page</h1>

<%= link_to 'Come in', cars_path, class: "btn btn-primary" %>